DROP TABLE PRODUCTS;
CREATE TABLE PRODUCTS
    (ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    PRICE INT,
    CODE VARCHAR(20));

INSERT INTO PRODUCTS VALUES(1, 'ITEM 1', 100, 'ITEM1');
INSERT INTO PRODUCTS VALUES(2, 'ITEM 2', 200, 'ITEM2');
INSERT INTO PRODUCTS VALUES(3, 'ITEM 3', 300, 'ITEM3');
INSERT INTO PRODUCTS VALUES(4, 'ITEM 4', 400, 'ITEM4');
INSERT INTO PRODUCTS VALUES(5, 'ITEM 5', 500, 'ITEM5');
